id: I991D6718
source: https://sakyaresearch.org
source_file: null
initial_creation_type: input
imported: '2022-06-18T21:03:57.804661'
last_modified: '2022-06-18T21:03:57.804673'
parser: null
source_metadata:
  title: Sakya Religious History by bCo brgyad khri chen rin po che (1919–2007)
  author: བཅོ་བརྒྱད་ཁྲི་ཆེན་ཐུབ་བསྟན་ལེགས་བཤད་རྒྱ་མཚོ།
  description: 'Digital version 1.0 {Tibetan}; master xml (completed: 2019-12-20);
    no thematic TEI markup'
  file_info:
  - 'Language: Tibetan'
  - 'Coverage: Full Text'
  - 'Accessible: publicly'
  responibilities:
  - Digital edition:ས་སྐྱ་ཞིབ་འཇུག་ཁང་། (src)
  - Text input:ཀུན་དགའ་རྡོ་རྗེ། (kun)
  - Editorial process:Mathias Fermer (mf)
  - TEI Encoding:ས་སྐྱ་ཞིབ་འཇུག་ཁང་།
  - TEI Markup:-
  - Revisions/Corrections:-
  text_witnesses: https://sakyaresearch.org/sources/3737
  bases:
    2f22:
      title: Sakya Religious History by bCo brgyad khri chen rin po che (1919–2007)
      order: 1
      base_file: 2f22.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
